sudo: required

services:
- docker

cache:
  directories:
  - "$HOME/.cache"

language: C

env:
  matrix:
  - OS=debian DIST=buster
  - OS=debian DIST=stretch
  - OS=debian DIST=jessie
  - OS=debian DIST=wheezy
  - OS=ubuntu DIST=bionic
  - OS=ubuntu DIST=xenial
  - OS=ubuntu DIST=trusty
  - OS=ubuntu DIST=precise
  - OS=el DIST=8
  - OS=el DIST=7
  - OS=el DIST=6
  - OS=fedora DIST=31
  - OS=fedora DIST=30
  - OS=fedora DIST=29
  - OS=fedora DIST=28
  - OS=fedora DIST=27
  - OS=fedora DIST=26
  - OS=fedora DIST=25
  - OS=fedora DIST=24
  - OS=debian DIST=buster ARCH=i386
  - OS=debian DIST=stretch ARCH=i386
  - OS=debian DIST=jessie ARCH=i386
  - OS=debian DIST=wheezy ARCH=i386
  - OS=ubuntu DIST=bionic ARCH=i386
  - OS=ubuntu DIST=xenial ARCH=i386
  - OS=ubuntu DIST=trusty ARCH=i386
  - OS=ubuntu DIST=precise ARCH=i386

jobs:
  allow_failures:
  - env: OS=debian DIST=jessie ARCH=i386

script:
- git describe --long
- make

before_deploy:
- git clone https://github.com/packpack/packpack.git packpack
- packpack/packpack

deploy:
  provider: releases
  api_key:
    secure: EljsD0rtgqo56H9eg/lHY/9NHYU2xH/wuBAF8WcdzHP9V7xnbe9mk3/gWXmd0AseIAbVn6C7TUyHxcJOPpqZ6HvdmN/dwWa4zhmTGRxQJvt3SCQ1TfLfVuh2a+xOdFxkCXWL1vu8u0CMEFpzzCOtQIk0r8YQ7/JfB79grAYC3IeG27IOH3dIDOY0ITpdD8Vhp7jt+3BSB9KfRe7FLdeyXG2pIZq9orhFPEhFYolJJhLyaJHGy+p6WITHaS+hVxm6/aAcHt/pX9Q/vswLIdAfVt3rdtehGb5x6Ngyunjq51e4fuxOjv07Oo9IHXMWO0Fn8p4C9SBqBwV2CmwiORmV2BdQ21aZzTuoRLYWEErCTmxbKIG0dYHPotwoxd719j4vriESvz9xQXxJVcxpcscs+vxQbEm9iPcdJJ6Wc4CyhVTMk3G4F4f1k4EsHGTbWi2z4FCE5m2ILE3rlxsTLp6qMgYdC0TnN7L9hWhv8xMX4Mvy8W+2clit0LvS+A78/SsITQYc8DyQj5ES1BJcYcUd9j2N6poUlbTIBHfEl1JzwnXsBLG8t9Pw7vNgFitKaYanDN+k7sQzUXIc/d+VXNkwkFpaclVs3ByeAaEbIL/X6Cb5h9L96EN654M+Mz3JrPdqZvi7ZAkLQsBfbjYZtHUdAOb/xzmA9muu9j4Rw5sEfBs=
  file_glob: true
  file: build/*.{deb,rpm}
  skip_cleanup: true
  on:
    tags: true
    repo: matricali/zokete
